### ISSUE TITLE
How can I set node_env to true on Heroku

### ISSUE THREAD

**Issue by murdoch** [ushahidi/platform-client#1085]
I have installed the platform-client on Heroku using the installer button.

The trouble is that I can't set node_env to 'production', when doing this because it throws up a load of gulp errors, presumably because gulp is a development dependency, and not a production one.

I image that this means my app builds assets on the fly, which is probably slower than running in production mode.

Is Ushahidi designed to be run in dev mode only? Is it supposed to be run in production mode at all? 

Do I need to clone the project, do the gulp stuff manually, and then deploy again from my own machine, with node env set to production? If so, are there specific instructions for how to run the phinx migrations etc? Am I supposed to push with git? 

I'm coming from a Rails background so PHP is like 'Greek' to me :)

Thanks in advance

**Comment by rowasc** [comment]
Hi, I'm sorry I missed this.

For future reference.

*Regarding heroku* 
 
I think for the heroku button we may need a bit more instructions or customization on that process so we can avoid situations where folks run it with the node server and instead encourage using a CDN to serve the frontend. 
I'll create a ticket to check out ways to improve the workflow with heroku... in case someone has the bandwith and wants to help.

**Regarding prod mode**
Ushahidi can run in production mode (it's how we run it for ushahidi.io)
To generate the frontend for production, you need to use the `gulp build` command which will generate the static assets to be uploaded (ie to a CDN or to your server), instead of running the dev server in prod.
The new setup documentation can be found here  https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/installing-for-production-environments


Thanks!
