### ISSUE TITLE
accessTokenExpires not being returned from server

### ISSUE THREAD

**Issue by cmacdonell** [ushahidi/platform-client#1242]
The authentication response is supposed to set a time the accessToken expires that is return from the server

from app/common/auth/authentication.service.js:192
```
var accessToken = authResponse.data.access_token;
console.log(authResponse.data);
Session.setSessionDataEntry('accessToken', accessToken);
Session.setSessionDataEntry('accessTokenExpires', authResponse.data.expires);
```

but the response does not include an "expires" field, but rather an "expires_in" offset (86400 is one day in seconds).

```
access_token:"eyJ0eXAiOiJKV1Qi....",
expires_in:86400,
refresh_token:"def50200...."
```

This causes the test "accessTokenExpires > now" to be false because "accessTokenExpires" is actually null since nothing is stored.

```
--- a/app/common/auth/authentication-interceptor.config.js
+++ b/app/common/auth/authentication-interceptor.config.js
@@ -91,7 +91,7 @@ function AuthInterceptor($rootScope, $injector, $q, CONST, Session, _) {
         var accessTokenExpires = Session.getSessionDataEntry('accessTokenExpires');
         var now = Math.floor(Date.now() / 1000);

-        if (accessToken !== undefined && accessToken !== null && accessTokenExpires > now) {
+        if (accessToken !== undefined && accessToken !== null ) {//&& accessTokenExpires > now) {
```

I'm willing to create a PR to fix this, but I'd like to confirm it is a problem and understand how best to proceed.

**Comment by rjmackay** [comment]
@cmacdonell can you confirm you're running the current `develop` branch of both client and api together?

If you look at https://github.com/ushahidi/platform-client/blob/develop/app/common/auth/authentication-interceptor.config.js#L34 or https://github.com/ushahidi/platform-client/blob/develop/app/common/auth/authentication.service.js#L93
you can see we use either `expires_in` or `expires` values depending on which is present. The token response changed in the latest codebase because we replaced the oauth code with Laravel Passport.

**Comment by cmacdonell** [comment]
Clearly my mistake. I'll close it. Sorry for the trouble.
